SECRET_KEY = "aabbcc"
CONTENT_ORIGIN = "http://pulp-content-primary:24816"
DATABASES = {"default": {"HOST": "postgres-primary", "ENGINE": "django.db.backends.postgresql", "NAME": "pulp_primary", "USER": "pulp", "PASSWORD": "password", "PORT": "5432", "CONN_MAX_AGE": 0, "OPTIONS": {"sslmode": "prefer"}}}
CACHE_ENABLED = True
REDIS_HOST = "redis-primary"
REDIS_PORT = 6379
REDIS_PASSWORD = ""
ANSIBLE_API_HOSTNAME = "http://pulp-api-primary:24817"
ANSIBLE_CONTENT_HOSTNAME = "http://pulp-content-primary:24816/pulp/content"
ALLOWED_IMPORT_PATHS = ["/tmp"]
ALLOWED_EXPORT_PATHS = ["/tmp"]
TOKEN_SERVER = "http://pulp-api-primary:24817/token/"
TOKEN_AUTH_DISABLED = False
TOKEN_SIGNATURE_ALGORITHM = "ES256"
PUBLIC_KEY_PATH = "/etc/pulp/keys/container_auth_public_key.pem"
PRIVATE_KEY_PATH = "/etc/pulp/keys/container_auth_private_key.pem"
ANALYTICS = False
STATIC_ROOT = "/var/lib/operator/static/"
ALLOWED_HOSTS = ['pulp-web-primary:8080', 'localhost', '127.0.0.1', '[::1]']